//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _14_02_2018_Template.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Blog
    {
        public int blog_id { get; set; }
        [DisplayName("Title")]
        public string blog_title { get; set; }
        [DisplayName("Content")]
        public string blog_content { get; set; }
        [DisplayName("Image")]
        public string blog_img { get; set; }
        [DisplayName("Category")]
        public Nullable<int> blog_category_id { get; set; }
        [DisplayName("Add Date")]
        public Nullable<System.DateTime> blog_add_date { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
