//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _14_02_2018_Template.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Contact
    {
        public int contact_id { get; set; }
        [DisplayName("Phone")]
        public string contact_phone { get; set; }
        [DisplayName("Email")]
        public string contact_email { get; set; }
        [DisplayName("Address")]
        public string contact_address { get; set; }
        [DisplayName("Work Time")]
        public string contact_work_time { get; set; }
    }
}
