//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _14_02_2018_Template.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Feature_Boxes
    {
        public int feature_boxes_id { get; set; }
        [DisplayName("Title")]
        public string feature_boxes_title { get; set; }
        [DisplayName("Icon")]
        public string feature_boxes_icon { get; set; }
        [DisplayName("Content")]
        public string feature_boxes_content { get; set; }
        [DisplayName("Url")]
        public string feature_boxes_url { get; set; }
    }
}
