//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _14_02_2018_Template.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Industry
    {
        public int industries_id { get; set; }
        [DisplayName("Title")]
        public string industries_title { get; set; }
        [DisplayName("Content")]
        public string industries_content { get; set; }
        [DisplayName("Image")]
        public string industries_img { get; set; }
        [DisplayName("Url")]
        public string industries_url { get; set; }
    }
}
