//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _14_02_2018_Template.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Menu
    {
        public int id { get; set; }
        [DisplayName("Name")]
        public string menu_name { get; set; }
        [DisplayName("Url")]
        public string menu_link { get; set; }
        [DisplayName("Title")]
        public string menu_title { get; set; }
    }
}
