//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _14_02_2018_Template.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Message
    {
        public int message_id { get; set; }
        [DisplayName("Name")]
        public string message_name { get; set; }
        [DisplayName("Email")]
        public string message_email { get; set; }
        [DisplayName("Web Url")]
        public string message_website_url { get; set; }
        [DisplayName("Content")]
        public string message_content { get; set; }
    }
}
