//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _14_02_2018_Template.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Slider
    {
        public int slider_id { get; set; }
        [DisplayName("Title")]
        public string slider_title { get; set; }
        [DisplayName("Image")]
        public string slider_img { get; set; }
        [DisplayName("First Url")]
        public string slider_first_url { get; set; }
        [DisplayName("Second Url")]
        public string slider_second_url { get; set; }
    }
}
