//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _14_02_2018_Template.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Testimonials_Slider
    {
        public int testimonials_slider_id { get; set; }
        [DisplayName("Icon")]
        public string testimonials_slider_icon { get; set; }
        [DisplayName("Content")]
        public string testimonials_slider_content { get; set; }
        [DisplayName("Author")]
        public string testimonials_slider_author { get; set; }
        [DisplayName("Position")]
        public string testimonials_slider_position { get; set; }
        [DisplayName("Image")]
        public string testimonials_slider_img { get; set; }
    }
}
